default:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - echo "before"
  after_script:
    - echo "after"

variables:
  VAR: hands-on-fast-and-secure-cicd-pipeline

first:
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - env
    - echo ${VAR}
    - echo ${GITLAB_OIDC_TOKEN}

second:
  variables:
    VAR: test
  script:
    - echo ${VAR}
    - aws